learning_user/basic_app/urls.py
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

































                                                              







              

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('special/', views.special,name='special'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

learning_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

      user = models.OneToOneField(User,on_delete = models.CASCADE)

      # additional attributes

      portfolio_site = models.URLField(blank = True)
      profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

      def __str__(self):
            return self.user.username

learning_user/basic_app/forms.py
from djando import forms
from basic_app.models import UserProfileInfo

class UserForm(models.ModelForm):

       password = forms.CharField(widget = forms.PasswordInput())

       class Meta():
           model = User
           fields = ('username','password','email')
    

class UserProfileInfoForm(models.ModelForm):
  
        class Meta():
 
            model = UserProfileInfoForm
            fields = ('profile_pic','portfolio_site')

learning_user/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

learning_user/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}

<html>
   <head>
     <title>BASE</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   </head>
   <body>
   <nav class = " navbar navbar-default navbar-static-top">  
     <div class="container">
       <ul class = "nav navbar-nav">
         <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
         <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
         <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li> 
       </ul>
     </div>
   </nav>
   <div>
   {% block body_block %}
   {% end_block %}
   </div>
   </body>
</html> 

learning_user/templates/basic_app/index.html
{% extends basic_app/base.html %}
   {% block body_block %}
   <div class = "jumbotron">
   <h1> Welcome to index page </h1>
   </div>
   <% endblock %}

learning_user/templates/basic_app/login.html
{% extends basic_app/base.html %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action = "{% url 'basic_app:user_login' %}" method='POST'>
  {% csrf_token %}

  <label for="username">Username</label>
  <input name="username" type="text" placeholder="Enter Username">
  
  <label for="password">Password</label>
  <input type="password" name="password">

  <input type="submit" value="Login">
  </form>
</div>

{% endblock %}

  

learning_user/templates/basic_app/registration.html
{% extends basic_app/base.html %}
{% load static %}

{% block body_block %}

<div class = "jumbotron">

   {% if registered %}
      <h1> Thank You for registering! </h1>
   {% else %}
      <h1> Register Here! <h1>
      <h3> FIll out the form: </h3>
  
      <form method="POST" enctype = "multipart/form-data">
   
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}

      <input type = "submit" value="Register">
      </form>
</div>
{% endblock %}
 



































                                                              







              